name: background_location_tracker_example
description: Demonstrates how to use the background_location_tracker plugin.
publish_to: 'none'

environment:
  # sdk: ">=2.12.0 <3.0.0"
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  background_location_tracker:
    path: ../
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.0
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  win32: 5.5.4
 
flutter:
  uses-material-design: true
